version: "3"
services:
  rmq:
    image: rabbitmq:3-management
    restart: always
#    profiles: ["queue"]
    networks:
    - myNetwork
    environment:
    - RABBITMQ_DEFAULT_USER=admin
    - RABBITMQ_DEFAULT_PASS=admin

